module.exports = function (grunt) {

    var headScripts = [
        '_ui/js/head-libs/*.js'
    ];

    var footScripts = [
        '_ui/js/foot-libs/*.js',
        '_ui/js/app.main.js',
        '_ui/js/components/*.js'
    ];

    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),

        sass: {
            dev: {
                options: {
                    sourcemap: true,
                    trace: true,
                    style: 'expanded',
                    debugInfo: true,
                    lineNumbers: true
                },
                files: {
                    '_ui/compiled/main-dev.css': '_ui/css/main.scss'
                }
            },
            prod: {
                options: {
                    sourcemap: false,
                    trace: false,
                    style: 'commpressed',
                    debugInfo: false,
                    lineNumbers: false
                },
                files: {
                    '_ui/compiled/main-prod.css': '_ui/css/main.scss'
                }
            }
        },

        cssmin: {
            dist: {
                options: {
                    banner: '/*! <%= pkg.name %> <%= pkg.version %> <%= grunt.template.today("yyyy-mm-dd HH:MM") %> */\n'
                },
                files: {
                    '_ui/compiled/main.min.css': ['_ui/compiled/main-prod.css']
                }
            }
        },

        concat: {
            dist: {
                files: {
                    '_ui/compiled/header-scripts.js': headScripts,
                    '_ui/compiled/footer-scripts.js': footScripts
                }
            },
        },

        uglify: {
            options: {
                banner: '/*! <%= pkg.name %> <%= pkg.version %> <%= grunt.template.today("yyyy-mm-dd HH:MM") %> */\n'
            },
            build: {
                files: {
                    '_ui/compiled/header-scripts.min.js': ['_ui/compiled/header-scripts.js'],
                    '_ui/compiled/footer-scripts.min.js': ['_ui/compiled/footer-scripts.js']
                }
            }
        },

        watch: {
            js: {
                files: ['_ui/js/*.js', '_ui/js/components/*.js'],
                options: {
                    livereload: true
                }
            },
            sass: {
                files: ['_ui/css/*.scss', '_ui/css/**/*.scss'],
                tasks: ['sass'],
                options: {
                    livereload: true
                }
            }
        }
    });

    // NPM tasks
    grunt.loadNpmTasks('grunt-contrib-concat');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-sass');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-cssmin');
    grunt.loadNpmTasks('grunt-shell');

    // Grunt tasks
    grunt.registerTask('default', ['sass:dev', 'scriptblocks']);
    grunt.registerTask('build', ['sass:prod', 'cssmin', 'scriptblocks', 'concat', 'uglify']);

    // Automate creation of scriptblock to be loaded in footer
    grunt.registerTask('scriptblocks', function(){
        var scriptHead = '<?php // AUTO-GENERATED BY GRUNT. To change this block edit Gruntfile.js, not this file! ?>' + '\n\n',
            scriptFoot = '<?php // AUTO-GENERATED BY GRUNT. To change this block edit Gruntfile.js, not this file! ?>' + '\n\n',
            headfiles,
            footfiles;

        headScripts.forEach(function(path) {
            headfiles = grunt.file.expand(path);

            headfiles.forEach(function(file){
                scriptHead += '<script src="/wp-content/themes/Wordpress-Boilerplate-Theme/' + file + '"></script>' + "\n";
            });

            grunt.file.write('parts/shared/header-scripts.php', scriptHead);
        });

        footScripts.forEach(function(path) {
            footfiles = grunt.file.expand(path);

            footfiles.forEach(function(file){
                scriptFoot += '<script src="/wp-content/themes/Wordpress-Boilerplate-Theme/' + file + '"></script>' + "\n";
            });

            grunt.file.write('parts/shared/footer-scripts.php', scriptFoot);
        });
    });
};